# Generated by Django 2.2.7 on 2019-11-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('clat', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_link', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='locations.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=100)),
                ('clong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('clat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('routes', models.ManyToManyField(related_name='locations', to='locations.Route')),
            ],
        ),
    ]
