# Generated by Django 2.2.7 on 2019-11-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='locations',
            field=models.ManyToManyField(blank=True, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='routes',
            field=models.ManyToManyField(blank=True, to='locations.Route'),
        ),
    ]
